### ISSUE TITLE
Auth MVP Review

### ISSUE THREAD

**Issue by mmcnulty20** [johnhcody/CheckRev#4]
- [x] Width of header matches width of other splash components
- [x] Width of searchbar increased to match other splash components
- [x] Business type icon font size to space between them ratio
- [x] Search by city optional
- [x] Github/Linked in links instead of modal
- [x] Login whitespace
- [x] Login subheader
- [x] Login Footer
- [x] Errors - currently not displayed
- [x] On focus/blur
- [x] Spacing on signup
- [x] Form layout
- [x] Button borders
- [x] Demo

**Comment by mmcnulty20** [comment]
- [x] Less whitespace between login form and footer
- [x] Less whitespace between first name and last name fields
- [x] Maybe not grey background onFocus, but optional
- [x] Different splash header styling when logged in

Looks great! :)

**Comment by johnhcody** [comment]
I hadn't been able to sign in to yelp to see the sign in header because my account got locked.  I just made a new account, and I think I would like to talk to you about how to attack the header
